GET http://localhost:3001

###

GET http://localhost:3001/health

###

GET http://localhost:3001/rocketleague

###

GET http://localhost:3001/error



###

GET http://localhost:3001/rocketleague/4

### 

POST http://localhost:3001/rocketleague
Content-Type: application/json

{
    "brand": "F",
    "model": "K"
}

### 

PUT http://localhost:3001/rocketleague/4
Content-Type: application/json

{
    "brand": "Fenec",
    "model": "Blanc Titane"
}

###

DELETE http://localhost:3001/rocketleague/2


### 

POST http://localhost:3001/auth/signin
Content-Type: application/json

{
    "email": "admin",
    "password": "admin"
}

###
POST http://localhost:3001/auth/signup
Content-Type: application/json

{
    "email": "admin",
    "password": "admin",
    "name": "admin",
    "phoneNumber": "123456789"
}